# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('employer', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=100)),
                ('first_registration', models.CharField(max_length=100)),
                ('date_of_first_registration', models.CharField(max_length=100)),
                ('additional_qualifications', models.TextField()),
                ('speciality', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='records')),
                ('synced', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
