# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_medic_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
