# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_medic_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='username',
        ),
    ]
