# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20170706_1928'),
        ('userprofile', '0003_auto_20170701_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='invitation_code_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitation.Invitation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
