# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170706_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Specialization'),
        ),
    ]
