# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170421_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsite',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialsite',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='socialsite',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialsite',
            name='website',
        ),
        migrations.AddField(
            model_name='doctor',
            name='website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialsite',
            name='social_site',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialsite',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/none/default.jpeg', null=True, upload_to='avatars'),
        ),
    ]
