# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20170425_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='user',
        ),
    ]
