# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20170708_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medic',
            old_name='status',
            new_name='invitation_status',
        ),
        migrations.AddField(
            model_name='medic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medic',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
