# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20170510_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
