# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 05:38
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20170710_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
