# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20170712_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('invitation_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='file_category',
            field=models.CharField(choices=[('Medical Records DB File', 'Medical Records DB file'), ('Gathered inhouse emails', 'Gathered inhouse emails')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
