# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20170716_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='sex',
            field=models.CharField(max_length=6),
        ),
    ]
