# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalcase',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Medical Cases'},
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='patient_gender',
            field=models.CharField(choices=[('', ''), ('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=6),
        ),
    ]
