# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcase',
            name='patient_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='purpose',
            field=models.CharField(max_length=250),
        ),
    ]
