# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcase', '0002_auto_20170514_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcase',
            name='medical_case_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalcase.MedicalCaseCategory'),
        ),
    ]
