# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcase', '0003_medicalcase_any_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcase',
            name='purpose',
            field=models.CharField(choices=[('I need help!', 'I need help!'), ('I found this case interesting.', 'I found this case interesting.'), ('I need help!', 'I need help!')], max_length=250),
        ),
    ]
