# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 07:25
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcase', '0006_auto_20170709_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcase',
            name='purpose',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('I need help to arrive at diagnosis', 'I need help to arrive at diagnosis'), ('Interesting case, a lot to learn', 'Interesting case, a lot to learn'), ('Rare case', 'Rare case'), ('Personal write up to improve skill', 'Personal write up to improve skill')], max_length=112, verbose_name='Reason for sharing medical case'),
        ),
    ]
