# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_suggestedinvitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedinvitee',
            name='invitation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestedinvitee',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
