# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_auto_20170711_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
